Configured Detekt for Static Analysis & Code Quality (#1071)
* Configured Detekt for Static Analysis & Code Quality

- Close #1070

* Test: Replace dependency guard with detekt

This commit replaces the dependency guard check with detekt in the build workflow.

* 🤖 Updates screenshots

* UI - Update ScaffoldNavActions & ExportScaffold

This commit updates the `ScaffoldNavActions` and `ExportScaffold` components to use `Row` instead of
 `Column` for layout.

The `tests_and_lint` workflow is also updated to depend on the `screenshot_tests` workflow. This ensures that screenshot tests are run before tests and lint checks.

* 🤖 Updates screenshots

* 🤖 Add workflow to automatically fix formatting issues

This commit introduces a new workflow that automatically fixes formatting issues if the detekt verification fails.

The workflow uses the
 `spotlessApply` gradle task to apply formatting changes and then pushes the changes using the `git-auto-commit-action`.

* 🤖 CI: Fix formatting with spotless if verification failed

This commit updates the CI workflow to use spotless for fixing formatting issues if verification fails.

The previous workflow
 used detekt for this purpose, but spotless is a more appropriate tool for this task.

---------

Co-authored-by: niyajali <niyajali@users.noreply.github.com>

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -35,7 +35,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        check: [ build_logic, spotless, dependency_guard ]
+        check: [ build_logic, spotless, detekt ]
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
@@ -48,12 +48,30 @@ jobs:
             ./gradlew check -p build-logic
           elif [ "${{ matrix.check }}" = "spotless" ]; then
             ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache
-          elif [ "${{ matrix.check }}" = "dependency_guard" ]; then
-            ./gradlew dependencyGuard
+          elif [ "${{ matrix.check }}" = "detekt" ]; then
+            ./gradlew detekt
           fi
 
+      - name: Upload Detekt Reports
+        if: ${{ matrix.check == 'detekt' && steps.run_check.outcome == 'success' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: detekt-reports
+          path: |
+            **/build/reports/detekt/detekt.md
 
-  tests_and_lint:
+      - name: Fix formatting if verification failed
+        id: fix_formatting
+        if: ${{ matrix.check == 'spotless' && steps.run_check.outcome == 'success' && github.event_name == 'pull_request' }}
+        run: ./gradlew spotlessApply --init-script gradle/init.gradle.kts --no-configuration-cache
+      - name: Push new changes if available
+        uses: stefanzweifel/git-auto-commit-action@v5
+        if: steps.fix_formatting.outcome == 'success'
+        with:
+          disable_globbing: true
+          commit_message: "🤖 Updates Formatting"
+
+  dependency_guard:
     needs: setup
     runs-on: ubuntu-latest
     steps:
@@ -62,17 +80,32 @@ jobs:
         with:
           distribution: 'zulu'
           java-version: 17
-      - name: Run tests and lint
+
+      - name: Check Dependency Guard
+        id: dependencyguard_verify
+        continue-on-error: true
+        run: ./gradlew dependencyGuard
+
+      - name: Prevent updating Dependency Guard baselines if this is a fork
+        id: checkfork_dependencyguard
+        if: steps.dependencyguard_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
         run: |
-          ./gradlew testDemoDebug :lint:test :app:lintProdRelease :lint:lint
-      - name: Upload reports
-        if: always()
-        uses: actions/upload-artifact@v4
+          echo "::error::Dependency Guard failed, please update baselines with: ./gradlew dependencyGuardBaseline" && exit 1
+
+        # Runs if previous job failed
+      - name: Generate new Dependency Guard baselines if verification failed and it's a PR
+        id: dependencyguard_baseline
+        if: steps.dependencyguard_verify.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew dependencyGuardBaseline
+
+      - name: Push new Dependency Guard baselines if available
+        uses: stefanzweifel/git-auto-commit-action@v5
+        if: steps.dependencyguard_baseline.outcome == 'success'
         with:
-          name: test-and-lint-reports
-          path: |
-            **/build/reports/lint-results-*.html
-            **/build/test-results/test*UnitTest/**.xml
+          file_pattern: '**/dependencies/*.txt'
+          disable_globbing: true
+          commit_message: "🤖 Updates baselines for Dependency Guard"
 
   screenshot_tests:
     needs: setup
@@ -99,8 +132,32 @@ jobs:
           disable_globbing: true
           commit_message: "🤖 Updates screenshots"
 
+  tests_and_lint:
+    needs: [ setup, screenshot_tests ]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version: 17
+      - name: Run tests and lint
+        run: |
+          ./gradlew testDemoDebug :lint:test :app:lintProdRelease :lint:lint
+      - name: Upload reports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-and-lint-reports
+          path: |
+            **/build/reports/lint-results-*.html
+            **/build/test-results/test*UnitTest/**.xml
+
+
+
+
   build:
-    needs: [ checks, tests_and_lint, screenshot_tests ]
+    needs: [ checks, dependency_guard, tests_and_lint, screenshot_tests ]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
